name: studenthub2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #c
  cupertino_icons: ^1.0.2
  cached_network_image: ^2.5.1
  #d
  dio: ^4.0.0
  #e
  encrypt: ^4.1.0
  #f
  #i
  intl: ^0.17.0
  image_picker: ^0.7.4
  #l
  flutter_local_notifications: ^5.0.0
  #m
  #o
  oktoast: ^3.0.0
  #p
  pin_code_fields: ^6.1.0
  permission_handler: ^6.1.1
  #q
  qr_code_scanner: ^0.3.5
  #s
  shared_preferences: ^2.0.5
  simple_animations: ^3.0.3
  supercharged: ^2.0.0
  share: ^2.0.1
  #t
  table_calendar: ^2.2.1
  #u
  url_launcher: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/test/

  fonts:
     - family:  Custom
       fonts:
        - asset: assets/fonts/Custom.ttf